# Generated by Django 4.2.7 on 2024-10-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='appointment',
        ),
    ]
