# Generated by Django 4.2.7 on 2024-10-19 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_contact_subject'),
        ('payments', '0002_remove_order_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='appoinment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.appointment'),
        ),
    ]
