# Generated by Django 4.2.7 on 2024-09-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='assignedDoctorId',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='symptoms',
        ),
    ]
