# Generated by Django 4.2.7 on 2024-09-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_patient_assigneddoctorid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
