# Generated by Django 4.2.7 on 2024-09-12 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_appointment_appointmenttime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='description',
        ),
    ]
