# Generated by Django 4.2.7 on 2024-09-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_appointment_available_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='assigned_token',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
