# Generated by Django 4.2.7 on 2024-09-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_appointment_assigned_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='available_tokens',
            new_name='total_tokens',
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_token',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
