# Generated by Django 4.2.7 on 2024-10-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
