# Generated by Django 4.2.7 on 2024-10-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
